# Neutron aliases
alias n='neutron'
alias nlist='neutron net-list'
alias rlist='neutron router-list'
alias slist='neutron subnet-list'
alias plist='neutron port-list'
alias rplist='neutron router-port-list'
alias riadd='neutron router-interface-add'
alias ridel='neutron router-interface-delete'
alias rgset='neutron router-gateway-set'
alias rgclear='neutron router-gateway-clear'
alias l3r='neutron l3-agent-list-hosting-router'
alias flist='neutron floatingip-list'
alias fcreate='neutron floatingip-create'
alias fass='neutron floatingip-associate'
alias fdel='neutron floatingip-delete'
